project:
  type: website
  preview: 
    port: 8080
    browser: false

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Blog"
  navbar:
    logo: ""
    left:
      - text: "Home"
        href: index.qmd 
    right:
      - about.qmd
      - icon: github
        href: https://github.com/digasx
      - icon: linkedin
        href: https://www.linkedin.com/in/rodrigoaraujodev/
format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css



