project:
  type: website
  preview: 
    port: 8080
    browser: false

website:
  description: "Um blog pessoal sobre desenvolvimento de software, tecnologia e afins."
  site-url: https://digasx.github.io/blog-digasx/ # you must change this appropriately for RSS feeds to work properly
  title: "Blog Pessoal de Rodrigo Araújo"
  navbar:
    logo: ""
    right:
      - about.qmd
      - icon: github
        href: https://github.com/digasx
      - icon: linkedin
        href: https://www.linkedin.com/in/rodrigoaraujodev/
format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css



